//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcherProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdFlight { get; set; }
        public string FlightNumber { get; set; }
        public int CompanyCode { get; set; }
        public int CompanyName { get; set; }
        public System.DateTime DateOfDeparture { get; set; }
        public Nullable<System.TimeSpan> TimeOfDeparture { get; set; }
        public int PointOfDepartureId { get; set; }
        public int PointOfArrivalId { get; set; }
        public int AirplaneId { get; set; }
        public int FreeSeatsCount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Companies Companies1 { get; set; }
        public virtual PointOfArrival PointOfArrival { get; set; }
        public virtual PointOfDeparture PointOfDeparture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
