//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcherProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdFlight { get; set; }
        public int CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int PointOfDeparture { get; set; }
        public int PointOfArrival { get; set; }
        public int Airplain { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual PointOfArrival PointOfArrival1 { get; set; }
        public virtual PointOfDeparture PointOfDeparture1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
