//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcherProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IdTicket { get; set; }
        public int Flight { get; set; }
        public int PassengerName { get; set; }
        public string TicketNumber { get; set; }
        public System.DateTime BookingDateTime { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
